# Generated by Django 4.2.27 on 2026-08-26 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fabrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Fábrica')),
            ],
            options={
                'verbose_name': 'Fábrica',
                'verbose_name_plural': 'Fábricas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Ubicación')),
                ('codigo', models.CharField(blank=True, max_length=50, verbose_name='Código')),
                ('fabrica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones', to='Motores.fabrica', verbose_name='Fábrica')),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
                'ordering': ['fabrica__nombre', 'nombre'],
                'unique_together': {('fabrica', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='SalaElectrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Electrical Room ID')),
                ('fabrica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salas_electricas', to='Motores.fabrica', verbose_name='Fábrica')),
                ('ubicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salas_electricas', to='Motores.ubicacion', verbose_name='Ubicación')),
            ],
            options={
                'verbose_name': 'Sala Eléctrica',
                'verbose_name_plural': 'Salas Eléctricas',
                'ordering': ['fabrica__nombre', 'nombre'],
                'unique_together': {('fabrica', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Motor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification_no', models.CharField(max_length=100, unique=True, verbose_name='Identification No. (ACS)')),
                ('equipment_description', models.CharField(max_length=255, verbose_name='Equipment Description')),
                ('power_hp', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Power Motor HP')),
                ('power_kw', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Power Motor kW')),
                ('power_kva', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Power Consumer kVA')),
                ('volt', models.CharField(blank=True, max_length=50, verbose_name='Volt')),
                ('current', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Current')),
                ('speed_1', models.CharField(blank=True, max_length=50, verbose_name='Speed 1')),
                ('speed_2', models.CharField(blank=True, max_length=50, verbose_name='Speed 2')),
                ('starting_type', models.CharField(blank=True, max_length=100, verbose_name='Starting, type')),
                ('protection_class', models.CharField(blank=True, max_length=50, verbose_name='Protect. Class')),
                ('insul_temp_rise', models.CharField(blank=True, max_length=50, verbose_name='Insul. Temp. Rise')),
                ('manufacturer_id', models.CharField(blank=True, max_length=150, verbose_name='Manufacturer ID')),
                ('supplier', models.CharField(blank=True, max_length=150, verbose_name='Supplier')),
                ('mv_lvd_mcc', models.CharField(blank=True, choices=[('MV', 'MV'), ('LVD', 'LVD'), ('MCC', 'MCC')], max_length=10, verbose_name='MV / LVD / MCC')),
                ('emergency_power_required', models.BooleanField(default=False, verbose_name='Emergency Power Required')),
                ('pastil_current_a', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Pastil Current A')),
                ('breaker_current_a', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Breaker Current A')),
                ('heater_serial', models.CharField(blank=True, max_length=100, verbose_name='Heater Serial')),
                ('heater_current', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Heater Current')),
                ('nema', models.CharField(blank=True, max_length=50, verbose_name='Nema')),
                ('serial', models.CharField(blank=True, max_length=100, verbose_name='Serial')),
                ('mounted', models.CharField(blank=True, max_length=100, verbose_name='Mounted')),
                ('frame', models.CharField(blank=True, max_length=50, verbose_name='Frame')),
                ('torque_nm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Torque Nm')),
                ('poles', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Poles')),
                ('fs', models.CharField(blank=True, max_length=50, verbose_name='F.S')),
                ('ron_ned_la', models.CharField(blank=True, max_length=50, verbose_name='Ron NED (LA)')),
                ('ron_ed_ll', models.CharField(blank=True, max_length=50, verbose_name='Ron ED (LL)')),
                ('efficiency', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Efficiency')),
                ('imagen_motor', models.ImageField(blank=True, null=True, upload_to='motores/motor/', verbose_name='Imagen Motor')),
                ('imagen_placa', models.ImageField(blank=True, null=True, upload_to='motores/placa/', verbose_name='Imagen Placa')),
                ('imagen_switches', models.ImageField(blank=True, null=True, upload_to='motores/switches/', verbose_name='Imagen Switches')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('fabrica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='motores', to='Motores.fabrica', verbose_name='Fábrica')),
                ('sala_electrica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motores', to='Motores.salaelectrica', verbose_name='Electrical Room ID')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='motores', to='Motores.ubicacion', verbose_name='Location ID')),
            ],
            options={
                'verbose_name': 'Motor',
                'verbose_name_plural': 'Motores',
                'ordering': ['identification_no'],
            },
        ),
    ]
