# Generated by Django 4.2.27 on 2026-08-27 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Motores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Fabricante')),
            ],
            options={
                'verbose_name': 'Fabricante',
                'verbose_name_plural': 'Fabricantes',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='motor',
            name='mv_lvd_mcc',
            field=models.CharField(blank=True, max_length=50, verbose_name='MV / LVD / MCC'),
        ),
        migrations.AlterField(
            model_name='motor',
            name='manufacturer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='motores', to='Motores.fabricante', verbose_name='Manufacturer ID'),
        ),
    ]
