# Generated by Django 4.2.27 on 2026-08-27 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Motores', '0003_seed_fabricantes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salaelectrica',
            options={'ordering': ['nombre'], 'verbose_name': 'Sala Eléctrica', 'verbose_name_plural': 'Salas Eléctricas'},
        ),
        migrations.AlterUniqueTogether(
            name='salaelectrica',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='salaelectrica',
            name='fabrica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salas_electricas', to='Motores.fabrica', verbose_name='Fábrica'),
        ),
        migrations.AlterField(
            model_name='salaelectrica',
            name='nombre',
            field=models.CharField(max_length=150, unique=True, verbose_name='Electrical Room ID'),
        ),
    ]
