# Generated by Django 4.2.27 on 2026-08-27 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Motores', '0005_seed_salas_electricas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ubicacion',
            options={'ordering': ['nombre'], 'verbose_name': 'Ubicación', 'verbose_name_plural': 'Ubicaciones'},
        ),
        migrations.AlterUniqueTogether(
            name='ubicacion',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='fabrica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ubicaciones', to='Motores.fabrica', verbose_name='Fábrica'),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='nombre',
            field=models.CharField(max_length=150, unique=True, verbose_name='Ubicación'),
        ),
    ]
