# Generated by Django 4.2.27 on 2026-08-27 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Motores', '0007_seed_ubicaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motor',
            name='fabrica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motores_fabrica', to='Motores.fabricante', verbose_name='Fábrica'),
        ),
    ]
