# Generated by Django 4.2.27 on 2026-08-27 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Motores', '0008_alter_motor_fabrica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motor',
            name='speed_2',
        ),
        migrations.AlterField(
            model_name='motor',
            name='speed_1',
            field=models.CharField(blank=True, max_length=100, verbose_name='Speed 1 - Speed 2'),
        ),
    ]
