# Generated by Django 4.2.27 on 2026-08-27 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Motores', '0009_remove_motor_speed_2_alter_motor_speed_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motor',
            name='starting_type',
        ),
        migrations.AddField(
            model_name='motor',
            name='starting',
            field=models.CharField(blank=True, max_length=100, verbose_name='Starting'),
        ),
        migrations.AddField(
            model_name='motor',
            name='tipo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Type'),
        ),
    ]
