# Generated by Django 4.2.27 on 2026-08-27 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Motores', '0010_remove_motor_starting_type_motor_starting_motor_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motor',
            name='heater_current',
            field=models.CharField(blank=True, max_length=100, verbose_name='Heater Current'),
        ),
        migrations.AlterField(
            model_name='motor',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='motores', to='Motores.ubicacion', verbose_name='Location ID'),
        ),
    ]
