# Generated by Django 4.2.27 on 2026-09-17 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Motores', '0012_motor_actualizado_por'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_actividad', models.CharField(choices=[('inspeccion', 'Inspección'), ('reparacion', 'Reparación'), ('cambio_repuesto', 'Cambio de repuesto'), ('instalacion', 'Instalación'), ('medicion', 'Medición eléctrica'), ('otro', 'Otro')], default='inspeccion', max_length=30, verbose_name='Tipo de actividad')),
                ('descripcion', models.TextField(verbose_name='Descripción de la actividad')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('motor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_actividad', to='Motores.motor', verbose_name='Motor')),
                ('operario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_mantenimiento_electrico', to=settings.AUTH_USER_MODEL, verbose_name='Operario')),
                ('sala_electrica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_actividad', to='Motores.salaelectrica', verbose_name='Sala Eléctrica')),
                ('ubicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_actividad', to='Motores.ubicacion', verbose_name='Ubicación')),
            ],
            options={
                'verbose_name': 'Registro de actividad',
                'verbose_name_plural': 'Registros de actividad',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
